export const data = [
	{
		id: 1,
		img: 'assets/imagenes/camilia.jpg',		
		nameProduct: 'Camilia',
		description: 'Solucion oral en envase unidosis',
		price: 100000,
		quantity: 1,
	},
	{
		id: 2,
		img: 'assets/imagenes/drenatox.jpg',		
		nameProduct: 'Drenatox',
		description: 'Desintoxica tu cuerpo',
		price: 50000,
		quantity: 1,
	},
	{
		id: 3,
		img: 'assets/imagenes/hypericum.jpg',		
		nameProduct: 'Hypericum',
		description: 'Medicamento Homeopatico simple',
		price: 60000,
		quantity: 1,
	},
	{
		id: 4,
		img: 'assets/imagenes/neurexan.jpg',
		nameProduct: 'Neurexan',
		description: 'Control natural de los estados nerviosos y alteraciones del sueño',
		price: 50000,
		quantity: 1,
	},
	{
		id: 5,
		img: 'assets/imagenes/phapax.jpg',		
		nameProduct: 'Phapax',
		description: 'Tratamiento y prevencion de migrañas',
		price: 100000,
		quantity: 1,
	},
	{
		id: 6,
		img: 'assets/imagenes/stodaline.jpg',
		nameProduct: 'Stodaline',
		description: 'Jarabe sin azucar',
		price: 75000,
		quantity: 1,
	},
	// Aquí pueden agregar más o modificar los productos existentes
];